version: "3.4"

services:
  server:
    image: ghcr.io/deephaven/server:0.19.1
    ports:
      - "${DEEPHAVEN_PORT:-10000}:10000"
    volumes:
      - ./data:/data
    environment:
      - START_OPTS=-Xmx4g
